Calendar with custom + fedocal interface, reminders, MessageBroken => Dispatcher
KaratekHD/defrag pull request #64
Opened 2021-08-22 13:16 UTC by why-not-try-calmer

- added a "Custom" community calendar with an interface slightly better than Fedocal
- added converters in both direction Custom <-> Fedocal
- added interface -- not implemented yet -- for push notifications
- added implementation for notification pollers (Jen's bots)
- added endpoints for adding and cancelling meetings

2021-08-23 18:40 UTC, why-not-try-calmer commented
@KaratekHD Can you take a look at the (new) dispatcher (formerly: MessagesBroker) and let me know if you find something not OK? Tomorrow the other half of my PR will be there (tests for the Calendar).

2021-08-26 18:35 UTC, KaratekHD requested changes
Code looks good, however it seems to break the docs module:
```
[2021-08-26 20:22:20,200 | ERROR] Task exception was never retrieved
future: <Task finished name='Task-3' coro=<make_search_set_indexes_in_parallel() done, defined at /home/jens/src/defrag-api/defrag/modules/docs.py:108> exception=TypeError("__init__() got an unexpected keyword argument 'closeOnResponse'")>
Traceback (most recent call last):
  File "/home/jens/src/defrag-api/defrag/modules/docs.py", line 110, in make_search_set_indexes_in_parallel
    leap, tw = await asyncio.gather(get_data("leap"), get_data("tumbleweed"))
  File "/home/jens/src/defrag-api/defrag/modules/docs.py", line 38, in get_data
    async with Req(indexes[source]["url"], closeOnResponse=False) as result:
TypeError: __init__() got an unexpected keyword argument 'closeOnResponse'
```
happens on load and this happens when accessing /docs/single/tumbleweed/...:
```
Traceback (most recent call last):
  File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 371, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/fastapi/routing.py", line 216, in app
    raw_response = await run_endpoint_function(
  File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/fastapi/routing.py", line 149, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/jens/src/defrag-api/defrag/modules/docs.py", line 137, in search_single_source_docs
    set_global_index("tumbleweed", make_tumbleweed_index(await get_data(source)))
  File "/home/jens/src/defrag-api/defrag/modules/docs.py", line 38, in get_data
    async with Req(indexes[source]["url"], closeOnResponse=False) as result:
TypeError: __init__() got an unexpected keyword argument 'closeOnResponse'
```

Also, the getting a calendar fails for me:
```
$ 
curl -X 'GET' \
  'http://localhost:8000/organizer/calendar/?start=2020-04-13%2000%3A00%3A00&end=2021-04-13%2000%3A00%3A00' \
  -H 'accept: application/json'
```
gives 
```json
{
  "query": {
    "service": "organizer",
    "item_key": null
  },
  "results_count": 0,
  "results": [],
  "error": null,
  "message": null
}
```
I put fedoras fedocal instance in the module file, and I would expect something to be in there. But maybe I'm doing sth wrong?

2021-08-26 18:35 UTC, KaratekHD commented on defrag/modules/dispatcher.py
> +        Exposes all due schedulables for pollings. When 'sync' is true, performs a destructive sync in the sense that
Mabye it would make sense to do this with some sort of client ID, so that it doesn't get removed for every subscribed service but only for one. Otherwise e.g. the Matrix bot might already have sent it to the Matrix rooms, but the Telegram bot is behind, didn't poll yet and would miss on that notification.

2021-08-26 18:35 UTC, KaratekHD commented on defrag/modules/organizer.py
> +FEDOCAL_URL = ""
Maybe we should ofload this to the config file?

2021-08-26 18:35 UTC, KaratekHD commented on defrag/modules/organizer.py
> +@app.post(f"/{__MOD_NAME__}/add_meetings/")
We need authentication here I think

2021-08-26 18:35 UTC, KaratekHD commented on defrag/modules/organizer.py
> +@app.post(f"/{__MOD_NAME__}/cancel_meeting/")
We need authentication here I think

2021-08-26 18:35 UTC, KaratekHD commented on defrag/modules/organizer.py
> +@app.post(f"/{__MOD_NAME__}/add_fedocal_meetings/")
We need authentication here I think

2021-08-26 18:35 UTC, KaratekHD commented on defrag/modules/organizer.py
> +async def post_reminders(reminder: Reminders) -> QueryResponse:
We need authentication here I think

2021-08-27 10:59 UTC, why-not-try-calmer commented
> Code looks good, however it seems to break the docs module:
> 
> ```
> [2021-08-26 20:22:20,200 | ERROR] Task exception was never retrieved
> future: <Task finished name='Task-3' coro=<make_search_set_indexes_in_parallel() done, defined at /home/jens/src/defrag-api/defrag/modules/docs.py:108> exception=TypeError("__init__() got an unexpected keyword argument 'closeOnResponse'")>
> Traceback (most recent call last):
>   File "/home/jens/src/defrag-api/defrag/modules/docs.py", line 110, in make_search_set_indexes_in_parallel
>     leap, tw = await asyncio.gather(get_data("leap"), get_data("tumbleweed"))
>   File "/home/jens/src/defrag-api/defrag/modules/docs.py", line 38, in get_data
>     async with Req(indexes[source]["url"], closeOnResponse=False) as result:
> TypeError: __init__() got an unexpected keyword argument 'closeOnResponse'
> ```
> 
> happens on load and this happens when accessing /docs/single/tumbleweed/...:
> 
> ```
> Traceback (most recent call last):
>   File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 371, in run_asgi
>     result = await app(self.scope, self.receive, self.send)
>   File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
>     return await self.app(scope, receive, send)
>   File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
>     await super().__call__(scope, receive, send)
>   File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/starlette/applications.py", line 112, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
>     raise exc from None
>   File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
>     await self.app(scope, receive, _send)
>   File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
>     raise exc from None
>   File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
>     await self.app(scope, receive, sender)
>   File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/starlette/routing.py", line 580, in __call__
>     await route.handle(scope, receive, send)
>   File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/starlette/routing.py", line 241, in handle
>     await self.app(scope, receive, send)
>   File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/starlette/routing.py", line 52, in app
>     response = await func(request)
>   File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/fastapi/routing.py", line 216, in app
>     raw_response = await run_endpoint_function(
>   File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/fastapi/routing.py", line 149, in run_endpoint_function
>     return await dependant.call(**values)
>   File "/home/jens/src/defrag-api/defrag/modules/docs.py", line 137, in search_single_source_docs
>     set_global_index("tumbleweed", make_tumbleweed_index(await get_data(source)))
>   File "/home/jens/src/defrag-api/defrag/modules/docs.py", line 38, in get_data
>     async with Req(indexes[source]["url"], closeOnResponse=False) as result:
> TypeError: __init__() got an unexpected keyword argument 'closeOnResponse'
> ```
> 
> Also, the getting a calendar fails for me:
> 
> ```
> $ 
> curl -X 'GET' \
>   'http://localhost:8000/organizer/calendar/?start=2020-04-13%2000%3A00%3A00&end=2021-04-13%2000%3A00%3A00' \
>   -H 'accept: application/json'
> ```
> 
> gives
> 
> ```json
> {
>   "query": {
>     "service": "organizer",
>     "item_key": null
>   },
>   "results_count": 0,
>   "results": [],
>   "error": null,
>   "message": null
> }
> ```
> 
> I put fedoras fedocal instance in the module file, and I would expect something to be in there. But maybe I'm doing sth wrong?

Thanks, the "closeOnResponse" was an un-removed leftover, thanks for spotting that. As for curling the calendar, it's out of the scope of the tests written so far but I suppose the datestrings are not encoded correctly. That's why I prefer writing tests that do _not_ depend on external requests for now.

2021-08-27 11:05 UTC, why-not-try-calmer commented on defrag/modules/dispatcher.py
> +        Exposes all due schedulables for pollings. When 'sync' is true, performs a destructive sync in the sense that
Absolutely, we need to discuss and agree on our authentication/authorization model. I'd like to have the big picture here ("who consumes what, when, what for?") and we need to agree on things so I'd rather not build too much from my speculation right now.

2021-08-27 11:05 UTC, why-not-try-calmer commented on defrag/modules/organizer.py
> +@app.post(f"/{__MOD_NAME__}/add_meetings/")
yup, see my answer above

2021-08-27 11:05 UTC, why-not-try-calmer commented on defrag/modules/organizer.py
> +@app.post(f"/{__MOD_NAME__}/cancel_meeting/")
+

2021-08-27 11:05 UTC, why-not-try-calmer commented on defrag/modules/organizer.py
> +@app.post(f"/{__MOD_NAME__}/add_fedocal_meetings/")
+

2021-08-27 11:05 UTC, why-not-try-calmer commented on defrag/modules/organizer.py
> +async def post_reminders(reminder: Reminders) -> QueryResponse:
+

2021-08-28 13:08 UTC, why-not-try-calmer commented
closing to make room for

2021-08-31 08:38 UTC, KaratekHD approved these changes

2021-08-31 09:07 UTC, merged