Simple reddit-like voting system
KaratekHD/defrag pull request #74
Opened 2021-09-01 09:21 UTC by why-not-try-calmer

2021-09-11 09:35 UTC, KaratekHD requested changes

2021-09-11 09:35 UTC, KaratekHD commented on defrag/modules/suggestions.py
> +@app.get(f"/{__MODULE_NAME__}/")
```
[2021-09-11 11:24:19,211 | ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/data/jens/Development/defrag-api/venv/lib64/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/data/jens/Development/defrag-api/venv/lib64/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/data/jens/Development/defrag-api/venv/lib64/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/data/jens/Development/defrag-api/venv/lib64/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/jens/Development/defrag-api/venv/lib64/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/data/jens/Development/defrag-api/venv/lib64/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/data/jens/Development/defrag-api/venv/lib64/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/data/jens/Development/defrag-api/venv/lib64/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/data/jens/Development/defrag-api/venv/lib64/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/data/jens/Development/defrag-api/venv/lib64/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/data/jens/Development/defrag-api/venv/lib64/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/data/jens/Development/defrag-api/venv/lib64/python3.8/site-packages/fastapi/routing.py", line 216, in app
    raw_response = await run_endpoint_function(
  File "/data/jens/Development/defrag-api/venv/lib64/python3.8/site-packages/fastapi/routing.py", line 149, in run_endpoint_function
    return await dependant.call(**values)
  File "/data/jens/Development/defrag-api/defrag/modules/suggestions.py", line 109, in get_suggestions
    if ok := results.is_ok:
AttributeError: 'list' object has no attribute 'is_ok'
```

2021-09-11 09:35 UTC, KaratekHD commented on defrag/modules/suggestions.py
> +        return QueryResponse(query=query, message="Thanks!")
Maybe return the suggestion id here?

2021-09-11 09:35 UTC, KaratekHD commented on defrag/modules/suggestions.py
> +async def vote_for_suggestion(voter_id: str, sugg_id: str, vote: int) -> QueryResponse:
How do we find out `sugg_id`?

2021-09-12 12:26 UTC, why-not-try-calmer commented
Thank you for testing more throughly than I did, should be fixed now

2021-09-16 21:07 UTC, merged

2021-09-17 07:46 UTC, why-not-try-calmer commented
Thank you!