Refactoring the cache
KaratekHD/defrag pull request #83
Opened 2021-10-03 18:25 UTC by why-not-try-calmer

A lot of simplifications and some abstractions. The idea is:
- when we need to cache through memoization, we simply decorate the endpoint handler with https://github.com/brainix/pottery#redis_cache (not implemented yet)
- when instead we need a more fine-grained data manipulation we do as suggested in this re-implementation (start from `reddit.py:get_reddit()` and follow the function calls to see where this leads (not tested yet)

Let me know if you think this approach is pleasant to use for you.

2021-10-19 11:08 UTC, KaratekHD requested changes

2021-10-19 11:08 UTC, KaratekHD commented on defrag/modules/reddit.py
>  async def get_reddit() -> QueryResponse:
This does not work:
```
INFO:     127.0.0.1:42256 - "GET /reddit/ HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/jens/.local/share/virtualenvs/defrag-api-021zzFKC/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/jens/.local/share/virtualenvs/defrag-api-021zzFKC/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/jens/.local/share/virtualenvs/defrag-api-021zzFKC/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/jens/.local/share/virtualenvs/defrag-api-021zzFKC/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/jens/.local/share/virtualenvs/defrag-api-021zzFKC/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/jens/.local/share/virtualenvs/defrag-api-021zzFKC/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/jens/.local/share/virtualenvs/defrag-api-021zzFKC/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/jens/.local/share/virtualenvs/defrag-api-021zzFKC/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/jens/.local/share/virtualenvs/defrag-api-021zzFKC/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/jens/.local/share/virtualenvs/defrag-api-021zzFKC/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/jens/.local/share/virtualenvs/defrag-api-021zzFKC/lib/python3.9/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/home/jens/.local/share/virtualenvs/defrag-api-021zzFKC/lib/python3.9/site-packages/fastapi/routing.py", line 216, in app
    raw_response = await run_endpoint_function(
  File "/home/jens/.local/share/virtualenvs/defrag-api-021zzFKC/lib/python3.9/site-packages/fastapi/routing.py", line 149, in run_endpoint_function
    return await dependant.call(**values)
  File "/data/jens/Development/defrag-api/defrag/modules/reddit.py", line 138, in get_reddit
    async with Run(query) as response:
  File "/data/jens/Development/defrag-api/defrag/modules/helpers/cache_manager.py", line 116, in __aenter__
    self.results = await Cache.services[self.query.service].store.fallback(self.query)
  File "/data/jens/Development/defrag-api/defrag/modules/reddit.py", line 78, in fallback
    await self.refresh()
  File "/data/jens/Development/defrag-api/defrag/modules/reddit.py", line 90, in refresh
    self.update_with([e.dict() for e in sorted_entries])
  File "/data/jens/Development/defrag-api/defrag/modules/reddit.py", line 75, in update_with
    self.container.extendleft(self.to_keep(items))
  File "/data/jens/Development/defrag-api/defrag/modules/reddit.py", line 68, in to_keep
    return [i.dict() for i in items]
  File "/data/jens/Development/defrag-api/defrag/modules/reddit.py", line 68, in <listcomp>
    return [i.dict() for i in items]
AttributeError: 'dict' object has no attribute 'dict'
```

2021-10-19 11:08 UTC, KaratekHD commented on defrag/modules/reddit.py
>  async def search(keywords: str) -> QueryResponse:
This does not work:
```
INFO:     127.0.0.1:42258 - "GET /reddit/search/?keywords=test HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/jens/.local/share/virtualenvs/defrag-api-021zzFKC/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/jens/.local/share/virtualenvs/defrag-api-021zzFKC/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/jens/.local/share/virtualenvs/defrag-api-021zzFKC/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/jens/.local/share/virtualenvs/defrag-api-021zzFKC/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/jens/.local/share/virtualenvs/defrag-api-021zzFKC/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/jens/.local/share/virtualenvs/defrag-api-021zzFKC/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/jens/.local/share/virtualenvs/defrag-api-021zzFKC/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/jens/.local/share/virtualenvs/defrag-api-021zzFKC/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/jens/.local/share/virtualenvs/defrag-api-021zzFKC/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/jens/.local/share/virtualenvs/defrag-api-021zzFKC/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/jens/.local/share/virtualenvs/defrag-api-021zzFKC/lib/python3.9/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/home/jens/.local/share/virtualenvs/defrag-api-021zzFKC/lib/python3.9/site-packages/fastapi/routing.py", line 216, in app
    raw_response = await run_endpoint_function(
  File "/home/jens/.local/share/virtualenvs/defrag-api-021zzFKC/lib/python3.9/site-packages/fastapi/routing.py", line 149, in run_endpoint_function
    return await dependant.call(**values)
  File "/data/jens/Development/defrag-api/defrag/modules/helpers/cache_manager.py", line 88, in inner
    func_call_key = hash(f.__name__, *args, **kwargs)
TypeError: hash() takes no keyword arguments
```

2021-10-19 13:32 UTC, why-not-try-calmer commented on defrag/modules/reddit.py
>  async def get_reddit() -> QueryResponse:
As I said it's not tested since I asked for feedback about the interface and I don't want to write tests if the interface is unpleasant to use for people. Just pushed the fix for this nonetheless.

2021-10-19 13:45 UTC, why-not-try-calmer commented on defrag/modules/reddit.py
>  async def search(keywords: str) -> QueryResponse:
Fixed too.

2021-10-22 16:42 UTC, why-not-try-calmer commented
(just my notes so that I don't forget)
Unittests (run one file after the other) marked as PASSED:
- dispatcher
- bugs
- reddit
- twitter
- organizer
- docs
- wikis
 - suggestions

Not passed yet:
- search

Issues noticed (I don't consider them to block this PR, but your calls guys):
- `bug = await as_async(bzapi.getbug)(bug_id)` <-- huge bottleneck, this not really our fault I think, the backend to this xmlrpc lib is apparently not very performant

2021-10-28 15:33 UTC, why-not-try-calmer commented
`test_search.py` (testing the global search feature) does not have a passing test yet. I'd like to request a review already because it's going to take some time. This one is huge.

2021-10-29 15:45 UTC, why-not-try-calmer commented
Okay I have all tests passing now. I'll start a new PR because this was a bit messy.

2021-10-29 16:02 UTC, closed without merging